#!/usr/bin/env python3
"""Compile the package's C# without a Unity licence.

The Unity test workflow only compiles this package when a Unity licence secret is
configured, and Unity disabled manual Personal-tier activation in 2024 — so on a
free seat nothing type-checks the C# at all. This script builds Editor/ and Tests/
with the .NET SDK against the UnityEngine/UnityEditor reference assemblies that
the Unity3D.SDK NuGet package ships (2021.1.14.1, the newest published), once
without and once with LIGHTMAP_UV_TOOL_FBX_EXPORTER (a stub stands in for the FBX
Exporter package), so both halves of every #if build. Anything the compiler
rejects fails the check with the repo-relative file and line.

Each project lives in its own folder under Projects/ so the two restores never
share an obj/ (one project.assets.json for both made the Tests build lose NUnit
whenever Editor restored last).

The 2021.1 references predate several APIs the code uses; each is bridged by a
line-preserving text substitution on the COPIED sources (never the repo), listed
in SHIMS with the reason. Keep that list short: every entry is an API the real
Unity build sees and this check cannot.

The Unity Test Framework is a separate package, absent from Unity3D.SDK. Its
UnityTest marker attribute is stubbed only in the generated compile-check sources;
coroutine execution is verified by the real Unity Test Runner.

Usage:
  python3 Tools~/compile_check.py                 # build both define variants
  python3 Tools~/compile_check.py --prepare-only  # only write .compile-check/ (SonarQube)
  python3 Tools~/compile_check.py --out DIR       # another build directory
  python3 Tools~/compile_check.py --root DIR      # another checkout's Editor/ and Tests/
                                                  # (the SonarQube workflow scans a PR's
                                                  # commit with this script from its own ref)
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent  # the package this script ships in; --root overrides
UNITY_SDK_VERSION = "2021.1.14.1"
NUNIT_VERSION = "3.13.3"
FBX_DEFINE = "LIGHTMAP_UV_TOOL_FBX_EXPORTER"

# (file glob, regex, replacement, why) — applied to the copied sources only.
SHIMS = [
    ("**/*.cs", r"AssetDatabase\.AssetEditingScope", "AssetEditingScopeShim",
     "AssetDatabase.AssetEditingScope is a 2022.1 nested type; the shim struct below stands in."),
    ("**/*.cs", r"Object\.FindObjectsByType<([A-Za-z0-9_.]+)>\(FindObjectsSortMode\.None\)",
     r"Object.FindObjectsOfType<\1>()",
     "Object.FindObjectsByType is 2022.2+; FindObjectsOfType is the 2021.1 equivalent."),
    ("**/*.cs", r"^using UnityEditor\.SceneManagement;$",
     "using UnityEditor.SceneManagement; using UnityEditor.Experimental.SceneManagement;",
     "PrefabStage / PrefabStageUtility moved out of Experimental in 2021.2."),
    ("**/*.cs", r"PrefabStageUtility\.OpenPrefab\(([^()]*)\)", r"((PrefabStage)null)",
     "PrefabStageUtility.OpenPrefab is 2021.2+; the check only needs the call to type."),
    ("**/RemeshNormalPreviewPacking.cs", r"UnityEditor\.Build\.NamedBuildTarget\.FromBuildTargetGroup\(([^()]*)\)", r"\1",
     "NamedBuildTarget is 2021.2+; the 2021.1 GetNormalMapEncoding overload takes BuildTargetGroup."),
]

SHIM_SOURCE = """// Generated by Tools~/compile_check.py — stands in for APIs the 2021.1 reference
// assemblies predate. Never part of the package.
namespace SashaRX.UnityMeshLab
{
    internal struct AssetEditingScopeShim : System.IDisposable { public void Dispose() { } }
}
namespace UnityEngine.TestTools
{
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public sealed class UnityTestAttribute : System.Attribute { }
}
"""

FBX_STUB_SOURCE = """// Generated by Tools~/compile_check.py — the FBX Exporter package's surface this
// package calls, so the LIGHTMAP_UV_TOOL_FBX_EXPORTER half of every #if compiles.
namespace UnityEditor.Formats.Fbx.Exporter
{
    public enum ExportFormat { ASCII, Binary }
    public class ExportModelOptions { public ExportFormat ExportFormat; public bool EmbedTextures; }
    public static class ModelExporter
    {
        public static string ExportObjects(string path, UnityEngine.Object[] objects, ExportModelOptions options = null) => path;
    }
}

// Autodesk's SDK surface: normalized static FBX output, the in-place channel edit
// (FbxDocumentEdit / FbxChannelWrite) and the node edit (FbxStructureEdit). Signatures mirror com.autodesk.fbx 5.1.
namespace Autodesk.Fbx
{
    public class FbxManager : System.IDisposable {
        public static FbxManager Create() => new FbxManager();
        public void SetIOSettings(FbxIOSettings io) { }
        public FbxIOSettings GetIOSettings() => new FbxIOSettings();
        public FbxIOPluginRegistry GetIOPluginRegistry() => new FbxIOPluginRegistry();
        public void Destroy() { }
        public void Dispose() { }
    }
    public class FbxIOPluginRegistry { public int FindWriterIDByDescription(string desc) => 0; }
    public class FbxIOSettings {
        public static FbxIOSettings Create(FbxManager manager, string name) => new FbxIOSettings();
        public void SetBoolProp(string name, bool value) { }
    }
    public static class Globals { public const string IOSROOT = ""; public const string EXP_FBX_EMBEDDED = ""; }
    public class FbxObject {
        public bool DisconnectSrcObject(FbxObject source) => true;
        public bool ConnectDstProperty(FbxProperty property) => true;
        public FbxProperty FindProperty(string name) => new FbxProperty();
        public string GetName() => "";
        public void SetName(string name) { }
        public FbxScene GetScene() => null;
        public virtual void Destroy() { }
    }
    public class FbxScene : FbxObject {
        public static FbxScene Create(FbxManager manager, string name) => new FbxScene();
        public int GetMaterialCount() => 0;
        public FbxSurfaceMaterial GetMaterial(string name) => null;
        public FbxSurfaceMaterial GetMaterial(int index) => null;
        public FbxGlobalSettings GetGlobalSettings() => new FbxGlobalSettings();
        public FbxNode GetRootNode() => new FbxNode();
        public void SetCurrentAnimationStack(FbxAnimStack stack) { }
    }
    public class FbxGlobalSettings {
        public FbxSystemUnit GetSystemUnit() => new FbxSystemUnit();
        public void SetSystemUnit(FbxSystemUnit unit) { }
        public FbxAxisSystem GetAxisSystem() => new FbxAxisSystem();
    }
    public class FbxSystemUnit { public static FbxSystemUnit m => new FbxSystemUnit(); public double GetScaleFactor() => 100; }
    public class FbxAxisSystem { public static FbxAxisSystem Max => new FbxAxisSystem(); public void DeepConvertScene(FbxScene scene) { } }
    public struct FbxDouble3 {
        public double X, Y, Z;
        public FbxDouble3(double x, double y, double z) { X = x; Y = y; Z = z; }
        public double this[int i] { get => 0; set { } }
    }
    public struct FbxVector4 {
        public double X, Y, Z, W;
        public FbxVector4(double x, double y, double z, double w = 1) { X = x; Y = y; Z = z; W = w; }
        public double this[int i] { get => 0; set { } }
        public static bool operator ==(FbxVector4 a, FbxVector4 b) => a.X == b.X && a.Y == b.Y && a.Z == b.Z && a.W == b.W;
        public static bool operator !=(FbxVector4 a, FbxVector4 b) => !(a == b);
        public override bool Equals(object obj) => obj is FbxVector4 v && v == this;
        public override int GetHashCode() => X.GetHashCode();
    }
    public class FbxProperty {
        public bool IsValid() => false;
        public FbxDouble3 GetFbxDouble3() => new FbxDouble3();
        public string GetString() => "";
        public int GetSrcObjectCount() => 0;
        public FbxObject GetSrcObject(int index) => null;
    }
    public class FbxPropertyString : FbxProperty {
        public FbxPropertyString Set(string value) => this;
        public string Get() => "";
    }
    public class FbxTexture : FbxObject {
        public FbxPropertyString UVSet => new FbxPropertyString();
        public enum ETextureUse { eStandard, eShadowMap, eLightMap, eSphericalReflectionMap, eSphereReflectionMap, eBumpNormalMap }
        public enum EMappingType { eNull, ePlanar, eSpherical, eCylindrical, eBox, eFace, eUV, eEnvironment }
        public void SetTextureUse(ETextureUse use) { }
        public void SetMappingType(EMappingType type) { }
    }
    public class FbxFileTexture : FbxTexture {
        public static FbxFileTexture Create(FbxObject container, string name) => new FbxFileTexture();
        public bool SetFileName(string name) => true;
        public bool SetRelativeFileName(string name) => true;
        public string GetFileName() => "";
        public string GetRelativeFileName() => "";
    }
    public class FbxPropertyDouble3 : FbxProperty {
        public FbxDouble3 Get() => new FbxDouble3();
        public FbxPropertyDouble3 Set(FbxDouble3 value) => this;
        public FbxAnimCurveNode GetCurveNode() => null;
        public FbxAnimCurveNode GetCurveNode(FbxAnimLayer layer, bool create) => null;
        public FbxAnimCurve GetCurve(FbxAnimLayer layer, string channel, bool create) => null;
    }
    public class FbxAnimCurveNode : FbxObject {
        public uint GetChannelsCount() => 0;
        public int GetCurveCount(uint channel) => 0;
        public FbxAnimCurve GetCurve(uint channel, uint index) => null;
    }
    public struct FbxTime { public static FbxTime FromSecondDouble(double seconds) => new FbxTime(); }
    public class FbxAnimCurve : FbxObject {
        public int KeyGetCount() => 0;
        public float KeyGetValue(int key) => 0;
        public void KeyModifyBegin() { }
        public void KeyModifyEnd() { }
        public int KeyAdd(FbxTime time) => 0;
        public void KeySet(int key, FbxTime time, float value) { }
    }
    public class FbxAnimLayer : FbxObject { public static FbxAnimLayer Create(FbxObject container, string name) => new FbxAnimLayer(); }
    public class FbxAnimStack : FbxObject {
        public static FbxAnimStack Create(FbxObject container, string name) => new FbxAnimStack();
        public bool AddMember(FbxObject member) => true;
    }
    public class FbxTransform { public enum EInheritType { eInheritRrSs, eInheritRSrs, eInheritRrs } }
    public class FbxPropertyEInheritType {
        public FbxTransform.EInheritType Get() => FbxTransform.EInheritType.eInheritRSrs;
        public FbxPropertyEInheritType Set(FbxTransform.EInheritType value) => this;
    }
    public class FbxEuler { public enum EOrder { eOrderXYZ, eOrderXZY, eOrderYZX, eOrderYXZ, eOrderZXY, eOrderZYX, eOrderSphericXYZ } }
    public class FbxAMatrix { public double Get(int row, int column) => 0; }
    public class FbxSurfaceMaterial : FbxObject {
        public static string sDiffuse => "DiffuseColor";
        public static string sShininess => "ShininessExponent";
    }
    public class FbxSurfaceLambert : FbxSurfaceMaterial { public FbxPropertyDouble3 Diffuse => new FbxPropertyDouble3(); }
    public class FbxSurfacePhong : FbxSurfaceLambert {
        public static FbxSurfacePhong Create(FbxObject container, string name) => new FbxSurfacePhong();
    }
    public class FbxNode : FbxObject {
        public enum EPivotSet { eSourcePivot, eDestinationPivot }
        public enum EShadingMode { eHardShading, eWireFrame, eFlatShading, eLightShading, eTextureShading, eFullShading }
        public void SetShadingMode(EShadingMode mode) { }
        public EShadingMode GetShadingMode() => EShadingMode.eHardShading;
        public FbxPropertyEInheritType InheritType => new FbxPropertyEInheritType();
        public FbxNode GetParent() => null;
        public FbxNode RemoveChild(FbxNode node) => node;
        public FbxNodeAttribute GetNodeAttribute() => null;
        public void SetRotationOrder(EPivotSet pivot, FbxEuler.EOrder order) { }
        public void GetRotationOrder(EPivotSet pivot, out int order) { order = 0; }
        public void SetRotationActive(bool value) { }
        public bool GetRotationActive() => false;
        public void SetRotationOffset(EPivotSet pivot, FbxVector4 v) { }
        public FbxVector4 GetRotationOffset(EPivotSet pivot) => new FbxVector4();
        public void SetRotationPivot(EPivotSet pivot, FbxVector4 v) { }
        public FbxVector4 GetRotationPivot(EPivotSet pivot) => new FbxVector4();
        public void SetPreRotation(EPivotSet pivot, FbxVector4 v) { }
        public void SetPostRotation(EPivotSet pivot, FbxVector4 v) { }
        public void SetScalingOffset(EPivotSet pivot, FbxVector4 v) { }
        public FbxVector4 GetScalingOffset(EPivotSet pivot) => new FbxVector4();
        public void SetScalingPivot(EPivotSet pivot, FbxVector4 v) { }
        public FbxVector4 GetScalingPivot(EPivotSet pivot) => new FbxVector4();
        public void SetGeometricTranslation(EPivotSet pivot, FbxVector4 v) { }
        public FbxVector4 GetGeometricTranslation(EPivotSet pivot) => new FbxVector4();
        public void SetGeometricRotation(EPivotSet pivot, FbxVector4 v) { }
        public FbxVector4 GetGeometricRotation(EPivotSet pivot) => new FbxVector4();
        public void SetGeometricScaling(EPivotSet pivot, FbxVector4 v) { }
        public FbxVector4 GetGeometricScaling(EPivotSet pivot) => new FbxVector4();
        public FbxAMatrix EvaluateGlobalTransform() => new FbxAMatrix();
        public int AddMaterial(FbxSurfaceMaterial material) => 0;
        public int GetMaterialCount() => 0;
        public FbxSurfaceMaterial GetMaterial(int index) => null;
        public FbxPropertyDouble3 LclTranslation => new FbxPropertyDouble3();
        public FbxPropertyDouble3 LclRotation => new FbxPropertyDouble3();
        public FbxPropertyDouble3 LclScaling => new FbxPropertyDouble3();
        public FbxVector4 GetPreRotation(EPivotSet pivot) => new FbxVector4();
        public FbxVector4 GetPostRotation(EPivotSet pivot) => new FbxVector4();
        public FbxMesh GetMesh() => null;
        public int GetChildCount() => 0;
        public FbxNode GetChild(int i) => null;
        public static FbxNode Create(FbxObject container, string name) => new FbxNode();
        public FbxNodeAttribute SetNodeAttribute(FbxNodeAttribute attribute) => attribute;
        public bool AddChild(FbxNode node) => true;
    }
    public class FbxNodeAttribute : FbxObject {
        public int GetNodeCount() => 0;
        public FbxNode GetNode(int index) => null;
    }
    public class FbxLayerContainer : FbxNodeAttribute {
        public int CreateLayer() => 0;
        public int GetLayerCount() => 0;
        public FbxLayer GetLayer(int index) => null;
    }
    public class FbxMesh : FbxLayerContainer {
        public static FbxMesh Create(FbxObject container, string name) => new FbxMesh();
        public void InitControlPoints(int count) { }
        public void BeginPolygon(int material = -1, int texture = -1, int group = -1, bool legacy = true) { }
        public void AddPolygon(int index, int textureUvIndex = -1) { }
        public void EndPolygon() { }
        public int GetControlPointsCount() => 0;
        public FbxVector4 GetControlPointAt(int i) => new FbxVector4();
        public void SetControlPointAt(FbxVector4 v, int i) { }
        public int GetPolygonCount() => 0;
        public int GetPolygonSize(int polygon) => 0;
        public int GetPolygonVertex(int polygon, int position) => 0;
        public int GetDeformerCount() => 0;
    }
    public struct FbxVector2 { public double X, Y; public FbxVector2(double x, double y) { X = x; Y = y; } }
    public struct FbxColor {
        public double mRed, mGreen, mBlue, mAlpha;
        public FbxColor(double red, double green, double blue, double alpha = 1) { mRed = red; mGreen = green; mBlue = blue; mAlpha = alpha; }
    }
    public class FbxLayerElementArray {
        public int GetCount() => 0;
        public bool SetCount(int count) => true;
        public int Add(int item) => 0;
        public int Add(FbxColor item) => 0;
        public int Add(FbxVector2 item) => 0;
        public int Add(FbxVector4 item) => 0;
        public void SetAt(int index, int item) { }
        public void SetAt(int index, FbxColor item) { }
        public void SetAt(int index, FbxVector2 item) { }
        public void SetAt(int index, FbxVector4 item) { }
    }
    public class FbxLayerElementArrayTemplateInt : FbxLayerElementArray { public int GetAt(int index) => 0; }
    public class FbxLayerElementArrayTemplateFbxVector2 : FbxLayerElementArray { public FbxVector2 GetAt(int index) => new FbxVector2(); }
    public class FbxLayerElementArrayTemplateFbxColor : FbxLayerElementArray { public FbxColor GetAt(int index) => new FbxColor(); }
    public class FbxLayerElement {
        public enum EType { eUnknown, eNormal, eBiNormal, eTangent, eMaterial, ePolygonGroup, eUV, eVertexColor, eSmoothing,
            eVertexCrease, eEdgeCrease, eHole, eUserData, eVisibility, eTextureDiffuse, eTextureDiffuseFactor, eTextureEmissive,
            eTextureEmissiveFactor, eTextureAmbient, eTextureAmbientFactor, eTextureSpecular, eTextureSpecularFactor,
            eTextureShininess, eTextureNormalMap, eTextureBump, eTextureTransparency, eTextureTransparencyFactor,
            eTextureReflection, eTextureReflectionFactor, eTextureDisplacement, eTextureDisplacementVector, eTypeCount }
        public enum EMappingMode { eNone, eByControlPoint, eByPolygonVertex, eByPolygon, eByEdge, eAllSame }
        public enum EReferenceMode { eDirect, eIndex, eIndexToDirect }
        public void SetMappingMode(EMappingMode mode) { }
        public void SetReferenceMode(EReferenceMode mode) { }
        public EMappingMode GetMappingMode() => EMappingMode.eNone;
        public EReferenceMode GetReferenceMode() => EReferenceMode.eDirect;
    }
    public class FbxLayerElementTemplateFbxVector2 : FbxLayerElement {
        public FbxLayerElementArrayTemplateFbxVector2 GetDirectArray() => new FbxLayerElementArrayTemplateFbxVector2();
        public FbxLayerElementArrayTemplateInt GetIndexArray() => new FbxLayerElementArrayTemplateInt();
    }
    public class FbxLayerElementTemplateFbxColor : FbxLayerElement {
        public FbxLayerElementArrayTemplateFbxColor GetDirectArray() => new FbxLayerElementArrayTemplateFbxColor();
        public FbxLayerElementArrayTemplateInt GetIndexArray() => new FbxLayerElementArrayTemplateInt();
    }
    public class FbxLayerElementArrayTemplateFbxVector4 : FbxLayerElementArray { public FbxVector4 GetAt(int index) => new FbxVector4(); }
    public class FbxLayerElementTemplateFbxVector4 : FbxLayerElement {
        public FbxLayerElementArrayTemplateFbxVector4 GetDirectArray() => new FbxLayerElementArrayTemplateFbxVector4();
        public FbxLayerElementArrayTemplateInt GetIndexArray() => new FbxLayerElementArrayTemplateInt();
    }
    public class FbxLayerElementNormal : FbxLayerElementTemplateFbxVector4 {
        public static FbxLayerElementNormal Create(FbxLayerContainer owner, string name) => new FbxLayerElementNormal();
    }
    public class FbxLayerElementTangent : FbxLayerElementTemplateFbxVector4 {
        public static FbxLayerElementTangent Create(FbxLayerContainer owner, string name) => new FbxLayerElementTangent();
    }
    public class FbxLayerElementBinormal : FbxLayerElementTemplateFbxVector4 {
        public static FbxLayerElementBinormal Create(FbxLayerContainer owner, string name) => new FbxLayerElementBinormal();
    }
    public class FbxLayerElementTemplateFbxSurfaceMaterial : FbxLayerElement {
        public FbxLayerElementArrayTemplateInt GetIndexArray() => new FbxLayerElementArrayTemplateInt();
    }
    public class FbxLayerElementMaterial : FbxLayerElementTemplateFbxSurfaceMaterial {
        public static FbxLayerElementMaterial Create(FbxLayerContainer owner, string name) => new FbxLayerElementMaterial();
    }
    public class FbxLayerElementUV : FbxLayerElementTemplateFbxVector2 {
        public static FbxLayerElementUV Create(FbxLayerContainer owner, string name) => new FbxLayerElementUV();
    }
    public class FbxLayerElementVertexColor : FbxLayerElementTemplateFbxColor {
        public static FbxLayerElementVertexColor Create(FbxLayerContainer owner, string name) => new FbxLayerElementVertexColor();
    }
    public class FbxLayer {
        public FbxLayerElementUV GetUVs(FbxLayerElement.EType type) => null;
        public FbxLayerElementVertexColor GetVertexColors() => null;
        public void SetUVs(FbxLayerElementUV uvs, FbxLayerElement.EType type) { }
        public void SetVertexColors(FbxLayerElementVertexColor colors) { }
        public FbxLayerElementNormal GetNormals() => null;
        public void SetNormals(FbxLayerElementNormal normals) { }
        public FbxLayerElementTangent GetTangents() => null;
        public void SetTangents(FbxLayerElementTangent tangents) { }
        public FbxLayerElementBinormal GetBinormals() => null;
        public void SetBinormals(FbxLayerElementBinormal binormals) { }
        public FbxLayerElementMaterial GetMaterials() => null;
        public void SetMaterials(FbxLayerElementMaterial materials) { }
    }
    public class FbxImporter : System.IDisposable {
        public static FbxImporter Create(FbxManager manager, string name) => new FbxImporter();
        public bool Initialize(string path, int format, FbxIOSettings io) => true;
        public void GetFileVersion(out int major, out int minor, out int revision) { major = 7; minor = 4; revision = 0; }
        public bool Import(FbxScene scene) => true;
        public void Dispose() { }
    }
    public class FbxExporter : System.IDisposable {
        public static FbxExporter Create(FbxManager manager, string name) => new FbxExporter();
        public bool Initialize(string path, int format, FbxIOSettings io) => true;
        public bool SetFileExportVersion(string version) => true;
        public bool Export(FbxScene scene) => true;
        public void Dispose() { }
    }
}
"""

NOWARN = "CS0649;CS0169;CS0414;CS0162;CS0219;CS0168;CS0618;CS0067;CS1998;CS8632;CS0105;NU1701"

EDITOR_CSPROJ = f"""<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>SashaRX.UnityMeshLab.Editor</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);{NOWARN}</NoWarn>
    <DefineConstants>$(DefineConstants);UNITY_EDITOR</DefineConstants>
    <DefineConstants Condition="'$(MeshLabFbx)' == 'true'">$(DefineConstants);{FBX_DEFINE}</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Editor/**/*.cs" LinkBase="Editor" />
    <Compile Include="../../Shims/UnityApiShims.cs" />
    <Compile Include="../../Shims/FbxExporterStub.cs" Condition="'$(MeshLabFbx)' == 'true'" />
    <PackageReference Include="Unity3D.SDK" Version="{UNITY_SDK_VERSION}" NoWarn="NU1701" />
  </ItemGroup>
</Project>
"""

TESTS_CSPROJ = f"""<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>SashaRX.UnityMeshLab.Tests.Editor</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);{NOWARN}</NoWarn>
    <DefineConstants>$(DefineConstants);UNITY_EDITOR;UNITY_INCLUDE_TESTS</DefineConstants>
    <DefineConstants Condition="'$(MeshLabFbx)' == 'true'">$(DefineConstants);{FBX_DEFINE}</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Tests/**/*.cs" LinkBase="Tests" />
    <ProjectReference Include="../Editor/Editor.csproj" />
    <PackageReference Include="Unity3D.SDK" Version="{UNITY_SDK_VERSION}" NoWarn="NU1701" />
    <PackageReference Include="NUnit" Version="{NUNIT_VERSION}" />
  </ItemGroup>
</Project>
"""

SLN = """Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Editor", "Projects\\Editor\\Editor.csproj", "{6B3C1A4E-0D4B-4D4F-9C3B-1F1C9B6D1E01}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Tests", "Projects\\Tests\\Tests.csproj", "{6B3C1A4E-0D4B-4D4F-9C3B-1F1C9B6D1E02}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{6B3C1A4E-0D4B-4D4F-9C3B-1F1C9B6D1E01}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{6B3C1A4E-0D4B-4D4F-9C3B-1F1C9B6D1E01}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{6B3C1A4E-0D4B-4D4F-9C3B-1F1C9B6D1E02}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{6B3C1A4E-0D4B-4D4F-9C3B-1F1C9B6D1E02}.Debug|Any CPU.Build.0 = Debug|Any CPU
	EndGlobalSection
EndGlobal
"""


def copy_sources(out: Path) -> None:
    for folder in ("Editor", "Tests"):
        dst = out / folder
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(ROOT / folder, dst, ignore=shutil.ignore_patterns("*.meta", "*.asmdef", "*.asmdef.meta"))


def apply_shims(out: Path) -> int:
    hits = 0
    for folder in ("Editor", "Tests"):
        for pattern, regex, repl, _why in SHIMS:
            rx = re.compile(regex, re.MULTILINE)
            for path in (out / folder).glob(pattern):
                text = path.read_text(encoding="utf-8")
                new, n = rx.subn(repl, text)
                if n:
                    path.write_text(new, encoding="utf-8")
                    hits += n
    return hits


def prepare(out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    copy_sources(out)
    shims = apply_shims(out)
    (out / "Shims").mkdir(exist_ok=True)
    (out / "Shims" / "UnityApiShims.cs").write_text(SHIM_SOURCE, encoding="utf-8")
    (out / "Shims" / "FbxExporterStub.cs").write_text(FBX_STUB_SOURCE, encoding="utf-8")
    for name, csproj in (("Editor", EDITOR_CSPROJ), ("Tests", TESTS_CSPROJ)):
        (out / "Projects" / name).mkdir(parents=True, exist_ok=True)
        (out / "Projects" / name / f"{name}.csproj").write_text(csproj, encoding="utf-8")
    (out / "MeshLab.sln").write_text(SLN, encoding="utf-8")
    print(f"prepared {out} ({shims} reference-gap substitution(s) applied to the copies)")


ERROR_RX = re.compile(r"^(?P<file>.+?)\((?P<line>\d+),(?P<col>\d+)\): error (?P<code>[A-Z]+\d+): (?P<msg>.*?)(?: \[.*\])?$")


def build(out: Path, fbx: bool) -> int:
    variant = "with" if fbx else "without"
    print(f"\n== dotnet build {variant} {FBX_DEFINE}")
    cmd = ["dotnet", "build", str(out / "MeshLab.sln"), "-nologo", "-v", "q", "--no-incremental",
           f"-p:MeshLabFbx={'true' if fbx else 'false'}", "-o", str(out / ("bin-fbx" if fbx else "bin"))]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    errors = []
    seen = set()
    for line in (proc.stdout + proc.stderr).splitlines():
        m = ERROR_RX.match(line.strip())
        if not m:
            continue
        rel = os.path.relpath(m.group("file"), out).replace(os.sep, "/")
        key = (rel, m.group("line"), m.group("code"))
        if key in seen:
            continue
        seen.add(key)
        errors.append((rel, int(m.group("line")), int(m.group("col")), m.group("code"), m.group("msg")))
    for rel, line, col, code, msg in errors:
        print(f"{rel}({line},{col}): error {code}: {msg}")
        if os.environ.get("GITHUB_ACTIONS"):
            print(f"::error file={rel},line={line},col={col},title={code}::{msg} ({variant} {FBX_DEFINE})")
    if proc.returncode != 0 and not errors:
        print(proc.stdout[-4000:])
        print(proc.stderr[-4000:])
    print(f"{'FAILED' if proc.returncode else 'ok'}: {len(errors)} error(s)")
    return proc.returncode


def main() -> int:
    global ROOT
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=str(ROOT / ".compile-check"), help="build directory (default .compile-check/)")
    ap.add_argument("--prepare-only", action="store_true", help="write the build directory and stop")
    ap.add_argument("--root", default=str(ROOT), help="the package checkout whose Editor/ and Tests/ to build (default: this script's)")
    args = ap.parse_args()
    ROOT = Path(args.root).resolve()
    if not (ROOT / "Editor").is_dir() or not (ROOT / "Tests").is_dir():
        print(f"error: --root {ROOT} has no Editor/ and Tests/ folders.", file=sys.stderr)
        return 2
    out = Path(args.out).resolve()
    if out == ROOT or (out / "Editor").resolve() == (ROOT / "Editor").resolve():
        print(f"error: --out must not be the package root ({ROOT}); the build directory's Editor/ and Tests/ "
              "are deleted and rewritten on every run.", file=sys.stderr)
        return 2
    prepare(out)
    if args.prepare_only:
        return 0
    rc = 0
    for fbx in (False, True):
        rc |= build(out, fbx)
    return 1 if rc else 0


if __name__ == "__main__":
    sys.exit(main())
