#!/usr/bin/env python3
"""Compile the package's C# without a Unity licence.

The Unity test workflow only compiles this package when a Unity licence secret is
configured, and Unity disabled manual Personal-tier activation in 2024 — so on a
free seat nothing type-checks the C# at all. This script builds Editor/ and Tests/
with the .NET SDK against the UnityEngine/UnityEditor reference assemblies that
the Unity3D.SDK NuGet package ships (2021.1.14.1, the newest published), once
without and once with LIGHTMAP_UV_TOOL_FBX_EXPORTER (a stub stands in for the FBX
Exporter package), so both halves of every #if build. Anything the compiler
rejects fails the check with the repo-relative file and line.

Each project lives in its own folder under Projects/ so the two restores never
share an obj/ (one project.assets.json for both made the Tests build lose NUnit
whenever Editor restored last).

The 2021.1 references predate four APIs the code uses; each is bridged by a
line-preserving text substitution on the COPIED sources (never the repo), listed
in SHIMS with the reason. Keep that list short: every entry is an API the real
Unity build sees and this check cannot.

Usage:
  python3 Tools~/compile_check.py                 # build both define variants
  python3 Tools~/compile_check.py --prepare-only  # only write .compile-check/ (SonarQube)
  python3 Tools~/compile_check.py --out DIR       # another build directory
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UNITY_SDK_VERSION = "2021.1.14.1"
NUNIT_VERSION = "3.13.3"
FBX_DEFINE = "LIGHTMAP_UV_TOOL_FBX_EXPORTER"

# (file glob, regex, replacement, why) — applied to the copied sources only.
SHIMS = [
    ("**/*.cs", r"AssetDatabase\.AssetEditingScope", "AssetEditingScopeShim",
     "AssetDatabase.AssetEditingScope is a 2022.1 nested type; the shim struct below stands in."),
    ("**/*.cs", r"Object\.FindObjectsByType<([A-Za-z0-9_.]+)>\(FindObjectsSortMode\.None\)",
     r"Object.FindObjectsOfType<\1>()",
     "Object.FindObjectsByType is 2022.2+; FindObjectsOfType is the 2021.1 equivalent."),
    ("**/*.cs", r"^using UnityEditor\.SceneManagement;$",
     "using UnityEditor.SceneManagement; using UnityEditor.Experimental.SceneManagement;",
     "PrefabStage / PrefabStageUtility moved out of Experimental in 2021.2."),
    ("**/*.cs", r"PrefabStageUtility\.OpenPrefab\(([^()]*)\)", r"((PrefabStage)null)",
     "PrefabStageUtility.OpenPrefab is 2021.2+; the check only needs the call to type."),
]

SHIM_SOURCE = """// Generated by Tools~/compile_check.py — stands in for APIs the 2021.1 reference
// assemblies predate. Never part of the package.
namespace SashaRX.UnityMeshLab
{
    internal struct AssetEditingScopeShim : System.IDisposable { public void Dispose() { } }
}
"""

FBX_STUB_SOURCE = """// Generated by Tools~/compile_check.py — the FBX Exporter package's surface this
// package calls, so the LIGHTMAP_UV_TOOL_FBX_EXPORTER half of every #if compiles.
namespace UnityEditor.Formats.Fbx.Exporter
{
    public enum ExportFormat { ASCII, Binary }
    public class ExportModelOptions { public ExportFormat ExportFormat; public bool EmbedTextures; }
    public static class ModelExporter
    {
        public static string ExportObjects(string path, UnityEngine.Object[] objects, ExportModelOptions options = null) => path;
    }
}
"""

NOWARN = "CS0649;CS0169;CS0414;CS0162;CS0219;CS0168;CS0618;CS0067;CS1998;CS8632;CS0105;NU1701"

EDITOR_CSPROJ = f"""<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>SashaRX.UnityMeshLab.Editor</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);{NOWARN}</NoWarn>
    <DefineConstants>$(DefineConstants);UNITY_EDITOR</DefineConstants>
    <DefineConstants Condition="'$(MeshLabFbx)' == 'true'">$(DefineConstants);{FBX_DEFINE}</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Editor/**/*.cs" LinkBase="Editor" />
    <Compile Include="../../Shims/UnityApiShims.cs" />
    <Compile Include="../../Shims/FbxExporterStub.cs" Condition="'$(MeshLabFbx)' == 'true'" />
    <PackageReference Include="Unity3D.SDK" Version="{UNITY_SDK_VERSION}" NoWarn="NU1701" />
  </ItemGroup>
</Project>
"""

TESTS_CSPROJ = f"""<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>SashaRX.UnityMeshLab.Tests.Editor</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);{NOWARN}</NoWarn>
    <DefineConstants>$(DefineConstants);UNITY_EDITOR;UNITY_INCLUDE_TESTS</DefineConstants>
    <DefineConstants Condition="'$(MeshLabFbx)' == 'true'">$(DefineConstants);{FBX_DEFINE}</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Tests/**/*.cs" LinkBase="Tests" />
    <ProjectReference Include="../Editor/Editor.csproj" />
    <PackageReference Include="Unity3D.SDK" Version="{UNITY_SDK_VERSION}" NoWarn="NU1701" />
    <PackageReference Include="NUnit" Version="{NUNIT_VERSION}" />
  </ItemGroup>
</Project>
"""

SLN = """Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Editor", "Projects\\Editor\\Editor.csproj", "{6B3C1A4E-0D4B-4D4F-9C3B-1F1C9B6D1E01}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Tests", "Projects\\Tests\\Tests.csproj", "{6B3C1A4E-0D4B-4D4F-9C3B-1F1C9B6D1E02}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{6B3C1A4E-0D4B-4D4F-9C3B-1F1C9B6D1E01}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{6B3C1A4E-0D4B-4D4F-9C3B-1F1C9B6D1E01}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{6B3C1A4E-0D4B-4D4F-9C3B-1F1C9B6D1E02}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{6B3C1A4E-0D4B-4D4F-9C3B-1F1C9B6D1E02}.Debug|Any CPU.Build.0 = Debug|Any CPU
	EndGlobalSection
EndGlobal
"""


def copy_sources(out: Path) -> None:
    for folder in ("Editor", "Tests"):
        dst = out / folder
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(ROOT / folder, dst, ignore=shutil.ignore_patterns("*.meta", "*.asmdef", "*.asmdef.meta"))


def apply_shims(out: Path) -> int:
    hits = 0
    for folder in ("Editor", "Tests"):
        for pattern, regex, repl, _why in SHIMS:
            rx = re.compile(regex, re.MULTILINE)
            for path in (out / folder).glob(pattern):
                text = path.read_text(encoding="utf-8")
                new, n = rx.subn(repl, text)
                if n:
                    path.write_text(new, encoding="utf-8")
                    hits += n
    return hits


def prepare(out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    copy_sources(out)
    shims = apply_shims(out)
    (out / "Shims").mkdir(exist_ok=True)
    (out / "Shims" / "UnityApiShims.cs").write_text(SHIM_SOURCE, encoding="utf-8")
    (out / "Shims" / "FbxExporterStub.cs").write_text(FBX_STUB_SOURCE, encoding="utf-8")
    for name, csproj in (("Editor", EDITOR_CSPROJ), ("Tests", TESTS_CSPROJ)):
        (out / "Projects" / name).mkdir(parents=True, exist_ok=True)
        (out / "Projects" / name / f"{name}.csproj").write_text(csproj, encoding="utf-8")
    (out / "MeshLab.sln").write_text(SLN, encoding="utf-8")
    print(f"prepared {out} ({shims} reference-gap substitution(s) applied to the copies)")


ERROR_RX = re.compile(r"^(?P<file>.+?)\((?P<line>\d+),(?P<col>\d+)\): error (?P<code>[A-Z]+\d+): (?P<msg>.*?)(?: \[.*\])?$")


def build(out: Path, fbx: bool) -> int:
    variant = "with" if fbx else "without"
    print(f"\n== dotnet build {variant} {FBX_DEFINE}")
    cmd = ["dotnet", "build", str(out / "MeshLab.sln"), "-nologo", "-v", "q", "--no-incremental",
           f"-p:MeshLabFbx={'true' if fbx else 'false'}", "-o", str(out / ("bin-fbx" if fbx else "bin"))]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    errors = []
    seen = set()
    for line in (proc.stdout + proc.stderr).splitlines():
        m = ERROR_RX.match(line.strip())
        if not m:
            continue
        rel = os.path.relpath(m.group("file"), out).replace(os.sep, "/")
        key = (rel, m.group("line"), m.group("code"))
        if key in seen:
            continue
        seen.add(key)
        errors.append((rel, int(m.group("line")), int(m.group("col")), m.group("code"), m.group("msg")))
    for rel, line, col, code, msg in errors:
        print(f"{rel}({line},{col}): error {code}: {msg}")
        if os.environ.get("GITHUB_ACTIONS"):
            print(f"::error file={rel},line={line},col={col},title={code}::{msg} ({variant} {FBX_DEFINE})")
    if proc.returncode != 0 and not errors:
        print(proc.stdout[-4000:])
        print(proc.stderr[-4000:])
    print(f"{'FAILED' if proc.returncode else 'ok'}: {len(errors)} error(s)")
    return proc.returncode


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=str(ROOT / ".compile-check"), help="build directory (default .compile-check/)")
    ap.add_argument("--prepare-only", action="store_true", help="write the build directory and stop")
    args = ap.parse_args()
    out = Path(args.out).resolve()
    if out == ROOT or (out / "Editor").resolve() == (ROOT / "Editor").resolve():
        print(f"error: --out must not be the package root ({ROOT}); the build directory's Editor/ and Tests/ "
              "are deleted and rewritten on every run.", file=sys.stderr)
        return 2
    prepare(out)
    if args.prepare_only:
        return 0
    rc = 0
    for fbx in (False, True):
        rc |= build(out, fbx)
    return 1 if rc else 0


if __name__ == "__main__":
    sys.exit(main())
